import type { HardeningStep } from '../types.ts';

export const systemHardeningSteps: HardeningStep[] = [
  {
    id: 'sys.lock-screen',
    title: 'Lock screen on screensaver',
    description: 'Require password immediately when screensaver activates',
    category: 'system-hardening',
    commands: [
      'defaults write com.apple.screensaver askForPassword -int 1',
      'defaults write com.apple.screensaver askForPasswordDelay -int 0',
    ],
    dangerLevel: 'low',
    requiresSudo: false,
  },
  {
    id: 'sys.show-hidden-files',
    title: 'Show hidden files in Finder',
    description: 'Make dotfiles and hidden files visible in Finder',
    category: 'system-hardening',
    commands: ['defaults write com.apple.finder AppleShowAllFiles -bool true'],
    dangerLevel: 'low',
    requiresSudo: false,
  },
  {
    id: 'sys.unhide-library',
    title: 'Unhide ~/Library',
    description: 'Remove the hidden flag from ~/Library folder',
    category: 'system-hardening',
    commands: ['chflags nohidden ~/Library'],
    dangerLevel: 'low',
    requiresSudo: false,
  },
  {
    id: 'sys.show-extensions',
    title: 'Show all filename extensions',
    description: 'Display file extensions for all files in Finder',
    category: 'system-hardening',
    commands: ['defaults write NSGlobalDomain AppleShowAllExtensions -bool true'],
    dangerLevel: 'low',
    requiresSudo: false,
  },
  {
    id: 'sys.no-icloud-default',
    title: 'Don\'t default save to iCloud',
    description: 'New documents save locally instead of iCloud by default',
    category: 'system-hardening',
    commands: ['defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false'],
    dangerLevel: 'low',
    requiresSudo: false,
  },
  {
    id: 'sys.disable-crash-reporter',
    title: 'Disable crash reporter dialog',
    description: 'Prevent the crash reporter dialog from appearing',
    category: 'system-hardening',
    commands: ['defaults write com.apple.CrashReporter DialogType none'],
    dangerLevel: 'low',
    requiresSudo: false,
  },
  {
    id: 'sys.disable-bonjour',
    title: 'Disable Bonjour multicast',
    description: 'Stop advertising services via multicast DNS',
    category: 'system-hardening',
    commands: ['sudo defaults write /Library/Preferences/com.apple.mDNSResponder.plist NoMulticastAdvertisements -bool YES'],
    dangerLevel: 'medium',
    requiresSudo: true,
  },
  {
    id: 'sys.umask-077',
    title: 'Set restrictive umask 077',
    description: 'New files are only readable by the owner',
    category: 'system-hardening',
    commands: ['sudo launchctl config user umask 077'],
    dangerLevel: 'medium',
    requiresSudo: true,
  },
  {
    id: 'sys.set-hostname',
    title: 'Set computer name',
    description: 'Set a generic computer name to avoid leaking personal info on networks',
    category: 'system-hardening',
    commands: [
      'sudo scutil --set ComputerName "__HOSTNAME__"',
      'sudo scutil --set LocalHostName "__HOSTNAME__"',
    ],
    dangerLevel: 'low',
    requiresSudo: true,
    promptForValue: { flag: '__HOSTNAME__', prompt: 'Enter computer name', default: 'MacBook' },
  },
];
